# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-22 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_user', models.CharField(max_length=10)),
                ('nombre_user', models.CharField(max_length=30)),
                ('apellido_user', models.CharField(max_length=30)),
                ('email_user', models.CharField(max_length=60)),
                ('escolaridad_user', models.CharField(max_length=30)),
                ('filiacion_user', models.CharField(max_length=100)),
            ],
        ),
    ]
